<?php

namespace Contentful\Tests\Management\Fixtures\E2E\CodeGenerator\Mapper;

use Contentful\Core\Api\Link;
use Contentful\Management\Mapper\BaseMapper;
use Contentful\Management\SystemProperties;
use Contentful\Tests\Management\Fixtures\E2E\CodeGenerator\Author;

/**
 * AuthorMapper class.
 *
 * This class was autogenerated.
 */
class AuthorMapper extends BaseMapper
{
    /**
     * {@inheritdoc}
     */
    public function map($resource, array $data): Author
    {
        return $this->hydrate($resource ?? Author::class, [
            'sys' => new SystemProperties($data['sys']),
            // Delegate the formatting of all fields
            'fields' => $this->formatFields($data['fields'] ?? []),
        ]);
    }

    /**
     * @param array $data
     *
     * @return array
     */
    private function formatFields(array $data): array
    {
        $fields = [];
        $fields['name'] = $data['name'] ?? null;
        $fields['location'] = $data['location'] ?? null;
        $fields['isActive'] = $data['isActive'] ?? null;
        $fields['misc'] = $data['misc'] ?? null;
        $fields['picture'] = [];
        foreach ($data['picture'] ?? [] as $locale => $value) {
            $fields['picture'][$locale] = new Link($value['sys']['id'], $value['sys']['linkType']);
        }

        return $fields;
    }
}
