<?php

namespace Contentful\Tests\Management\Fixtures\E2E\CodeGenerator\Mapper;

use Contentful\Core\Api\DateTimeImmutable;
use Contentful\Core\Api\Link;
use Contentful\Management\Mapper\BaseMapper;
use Contentful\Management\SystemProperties;
use Contentful\Tests\Management\Fixtures\E2E\CodeGenerator\BlogPost;

/**
 * BlogPostMapper class.
 *
 * This class was autogenerated.
 */
class BlogPostMapper extends BaseMapper
{
    /**
     * {@inheritdoc}
     */
    public function map($resource, array $data): BlogPost
    {
        return $this->hydrate($resource ?? BlogPost::class, [
            'sys' => new SystemProperties($data['sys']),
            // Delegate the formatting of all fields
            'fields' => $this->formatFields($data['fields'] ?? []),
        ]);
    }

    /**
     * @param array $data
     *
     * @return array
     */
    private function formatFields(array $data): array
    {
        $fields = [];
        $fields['title'] = $data['title'] ?? null;
        $fields['body'] = $data['body'] ?? null;
        $fields['publishedAt'] = [];
        foreach ($data['publishedAt'] ?? [] as $locale => $value) {
            $fields['publishedAt'][$locale] = new DateTimeImmutable($value);
        }
        $fields['image'] = [];
        foreach ($data['image'] ?? [] as $locale => $value) {
            $fields['image'][$locale] = new Link($value['sys']['id'], $value['sys']['linkType']);
        }
        $fields['related'] = [];
        foreach ($data['related'] ?? [] as $locale => $value) {
            $fields['related'][$locale] = \array_map(function (array $link): Link {
                return new Link($link['sys']['id'], $link['sys']['linkType']);
            }, $value);
        }
        $fields['tags'] = $data['tags'] ?? null;
        $fields['author'] = [];
        foreach ($data['author'] ?? [] as $locale => $value) {
            $fields['author'][$locale] = new Link($value['sys']['id'], $value['sys']['linkType']);
        }

        return $fields;
    }
}
