orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

version: 2.1

workflows:
  version: 2

  main:
    jobs:
      - lint
      - test72
      - test73
      - test74
      - test80
      - docs_build:
          requires:
            - lint
            - test74
            - test80
            - test81
          filters:
            branches:
              only: master

jobs:
  lint:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - checkout
      - run: { name: "Install dependencies", command: sudo composer self-update && composer install -n --prefer-dist }
      - run:
          name: Syntax tests
          command: |
            composer run lint-syntax

  test74:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install -y libxml2-dev && sudo apt-get clean -y && sudo docker-php-ext-install soap
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

  test80:
    docker:
      - image: circleci/php:8.0-cli
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install -y libxml2-dev && sudo apt-get clean -y && sudo docker-php-ext-install soap
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist --ignore-platform-reqs" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }

  test81:
    docker:
      - image: circleci/php:8.1-cli
    steps:
      - checkout
      - run: sudo apt-get update -y && sudo apt-get install -y libxml2-dev && sudo apt-get clean -y && sudo docker-php-ext-install soap
      - run: { name: "Install dependencies", command: "sudo composer self-update && composer install -n --prefer-dist --ignore-platform-reqs" }
      - run: { name: "Test suite", command: "composer test-quick-fail" }



  docs_build:
    environment:
      TRAVIS_REPO_SLUG: contentful/contentful-management.php
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - checkout
      - run: {name: "Make docs", command: "sh ./scripts/prepare-docs.sh" }
      - gh-pages/deploy:
          build-dir: build/docs
          ssh-fingerprints: 39:16:7c:6f:bb:e5:08:7a:6d:68:6f:0f:3a:73:64:a5
