<?php

namespace Contentful\Tests\Management\Fixtures\E2E\CodeGenerator;

use Contentful\Core\Api\Link;
use Contentful\Management\Resource\Asset;
use Contentful\Management\Resource\Entry;

/**
 * Author class.
 *
 * This class was autogenerated.
 */
class Author extends Entry
{
    /**
     * Author constructor.
     */
    public function __construct()
    {
        parent::__construct('author');
    }

    /**
     * Returns the "name" field.
     *
     * @param string $locale
     *
     * @return string|null
     */
    public function getName(string $locale = 'en-US')
    {
        return $this->getField('name', $locale);
    }

    /**
     * Sets the "name" field.
     *
     * @param string      $locale
     * @param string|null $value
     *
     * @return static
     */
    public function setName(string $locale = 'en-US', string $value = null)
    {
        return $this->setField('name', $locale, $value);
    }

    /**
     * Returns the "location" field.
     *
     * @param string $locale
     *
     * @return float[]|null
     */
    public function getLocation(string $locale = 'en-US')
    {
        return $this->getField('location', $locale);
    }

    /**
     * Sets the "location" field.
     *
     * @param string       $locale
     * @param float[]|null $value
     *
     * @return static
     */
    public function setLocation(string $locale = 'en-US', array $value = null)
    {
        return $this->setField('location', $locale, $value);
    }

    /**
     * Returns the "isActive" field.
     *
     * @param string $locale
     *
     * @return bool|null
     */
    public function getIsActive(string $locale = 'en-US')
    {
        return $this->getField('isActive', $locale);
    }

    /**
     * Sets the "isActive" field.
     *
     * @param string    $locale
     * @param bool|null $value
     *
     * @return static
     */
    public function setIsActive(string $locale = 'en-US', bool $value = null)
    {
        return $this->setField('isActive', $locale, $value);
    }

    /**
     * Returns the "misc" field.
     *
     * @param string $locale
     *
     * @return mixed|null
     */
    public function getMisc(string $locale = 'en-US')
    {
        return $this->getField('misc', $locale);
    }

    /**
     * Sets the "misc" field.
     *
     * @param string     $locale
     * @param mixed|null $value
     *
     * @return static
     */
    public function setMisc(string $locale = 'en-US', $value = null)
    {
        return $this->setField('misc', $locale, $value);
    }

    /**
     * Returns the "picture" field.
     *
     * @param string $locale
     *
     * @return Link|null
     */
    public function getPicture(string $locale = 'en-US')
    {
        return $this->getField('picture', $locale);
    }

    /**
     * Sets the "picture" field.
     *
     * @param string    $locale
     * @param Link|null $value
     *
     * @return static
     */
    public function setPicture(string $locale = 'en-US', Link $value = null)
    {
        return $this->setField('picture', $locale, $value);
    }

    /**
     * Returns the resolved "picture" link.
     *
     * @param string $locale
     *
     * @return Asset
     */
    public function resolvePictureLink(string $locale = 'en-US')
    {
        $parameters = [
            // Representation of the URI parameters
            'space' => $this->sys->getSpace()->getId(),
            'environment' => $this->sys->getEnvironment()->getId(),
        ];

        return $this->client->resolveLink($this->getField('picture', $locale), $parameters);
    }
}
