<?php

namespace Contentful\Tests\Management\Fixtures\Integration\CodeGenerator\Mapper;

use Contentful\Link;
use Contentful\Management\ApiDateTime;
use Contentful\Management\Mapper\BaseMapper;
use Contentful\Management\SystemProperties;
use Contentful\Tests\Management\Fixtures\Integration\CodeGenerator\BlogPost;

/**
 * BlogPostMapper class.
 *
 * This class was autogenerated.
 */
class BlogPostMapper extends BaseMapper
{
    /**
     * {@inheritdoc}
     */
    public function map($resource, array $data): BlogPost
    {
        return $this->hydrate($resource ?? BlogPost::class, [
            'sys' => new SystemProperties($data['sys']),
            // Delegate the formatting of all fields
            'fields' => $this->formatFields($data['fields'] ?? []),
        ]);
    }

    /**
     * @param array $data
     *
     * @return array
     */
    private function formatFields(array $data): array
    {
        $fields = [];
        $fields['title'] = $data['title'] ?? null;
        $fields['isPublished'] = $data['isPublished'] ?? null;
        $fields['publishedAt'] = [];
        foreach ($data['publishedAt'] ?? [] as $locale => $value) {
            $fields['publishedAt'][$locale] = new ApiDateTime($value);
        }
        $fields['previous'] = [];
        foreach ($data['previous'] ?? [] as $locale => $value) {
            $fields['previous'][$locale] = new Link($value['sys']['id'], $value['sys']['linkType']);
        }
        $fields['heroImage'] = [];
        foreach ($data['heroImage'] ?? [] as $locale => $value) {
            $fields['heroImage'][$locale] = new Link($value['sys']['id'], $value['sys']['linkType']);
        }
        $fields['randomEntry'] = [];
        foreach ($data['randomEntry'] ?? [] as $locale => $value) {
            $fields['randomEntry'][$locale] = new Link($value['sys']['id'], $value['sys']['linkType']);
        }
        $fields['misc'] = $data['misc'] ?? null;
        $fields['body'] = $data['body'] ?? null;
        $fields['minimumAge'] = $data['minimumAge'] ?? null;
        $fields['location'] = $data['location'] ?? null;
        $fields['rating'] = $data['rating'] ?? null;
        $fields['images'] = [];
        foreach ($data['images'] ?? [] as $locale => $value) {
            $fields['images'][$locale] = array_map(function (array $link): Link {
                return new Link($link['sys']['id'], $link['sys']['linkType']);
            }, $value);
        }
        $fields['related'] = [];
        foreach ($data['related'] ?? [] as $locale => $value) {
            $fields['related'][$locale] = array_map(function (array $link): Link {
                return new Link($link['sys']['id'], $link['sys']['linkType']);
            }, $value);
        }
        $fields['tags'] = $data['tags'] ?? null;

        return $fields;
    }
}
