<?php

/**
 * This file is part of the contentful-management.php package.
 *
 * @copyright 2015-2017 Contentful GmbH
 * @license   MIT
 */
declare(strict_types=1);

namespace Contentful\Management\CodeGenerator;

use Contentful\Link;
use Contentful\Management\ApiDateTime;
use Contentful\Management\Resource\Asset;
use Contentful\Management\Resource\ContentType;
use Contentful\Management\Resource\ContentType\Field\ArrayField;
use Contentful\Management\Resource\ContentType\Field\FieldInterface;
use Contentful\Management\Resource\ContentType\Field\LinkField;
use Contentful\Management\Resource\ContentType\Validation\LinkContentTypeValidation;
use Contentful\Management\Resource\Entry as EntryResource;
use Contentful\Management\Resource\ResourceInterface;
use PhpParser\Node;
use PhpParser\Node\Stmt\Class_;
use PhpParser\Node\Stmt\ClassMethod;

/**
 * Entry class.
 */
class Entry extends BaseCodeGenerator
{
    /**
     * @var array
     */
    private $uses = [];

    /**
     * Restore the uses array to default values.
     */
    private function setDefaultUses()
    {
        $this->uses = [
            'asset' => false,
            'resource_interface' => false,
            'link' => false,
            'date' => false,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function generate(array $params): string
    {
        $contentType = $params['content_type'];
        $namespace = $params['namespace'];

        $this->setDefaultUses();

        $class = $this->generateClass($contentType);

        $stmts = $this->generateUses([
            EntryResource::class,
            $this->uses['date'] ? ApiDateTime::class : null,
            $this->uses['asset'] ? Asset::class : null,
            $this->uses['link'] ? Link::class : null,
            $this->uses['resource_interface'] ? ResourceInterface::class : null,
        ]);

        $stmts[] = $class;

        return $this->render(
            new Node\Stmt\Namespace_(new Node\Name($namespace), $stmts)
        );
    }

    /**
     * @param ContentType $contentType
     *
     * @return Class_
     */
    private function generateClass(ContentType $contentType): Class_
    {
        $className = $this->convertToStudlyCaps($contentType->getId());

        return new Node\Stmt\Class_(
            $className,
            [
                'extends' => new Node\Name('Entry'),
                'stmts' => $this->generateClassMethods($contentType),
            ],
            $this->generateCommentAttributes(\sprintf(
                "\n".'/**
                * %s class.
                *
                * This class was autogenerated.
                */',
                $className
            ))
        );
    }

    /**
     * @param ContentType $contentType
     *
     * @return ClassMethod[]
     */
    private function generateClassMethods(ContentType $contentType): array
    {
        $stmts = [
            $this->generateConstructor($contentType),
        ];

        foreach ($contentType->getFields() as $field) {
            $type = $this->getFieldType($field);
            if ($type == 'Link' || $type == 'Link[]') {
                $this->uses['link'] = true;
            }
            if ($type == 'ApiDateTime') {
                $this->uses['date'] = true;
            }

            $stmts[] = $this->generateGetter($field, $type);
            $stmts[] = $this->generateSetter($field, $type);

            if ($type == 'Link') {
                $stmts[] = $this->generateLinkResolverMethod($field);
            }
            if ($type == 'Link[]') {
                $stmts[] = $this->generateArrayLinkResolverMethod($field);
            }
        }

        return $stmts;
    }

    /**
     * Generates the following code.
     *
     * ```
     * public function __construct()
     * {
     *     parent::__costruct('<contentTypeId>');
     * }
     * ```
     *
     * @param ContentType $contentType
     *
     * @return ClassMethod
     */
    private function generateConstructor(ContentType $contentType): ClassMethod
    {
        return new ClassMethod(
            '__construct',
            [
                'flags' => Node\Stmt\Class_::MODIFIER_PUBLIC,
                'stmts' => [
                    new Node\Expr\StaticCall(
                        new Node\Name('parent'),
                        '__construct',
                        [
                            new Node\Arg(new Node\Scalar\String_($contentType->getId())),
                        ]
                    ),
                ],
            ],
            $this->generateCommentAttributes(\sprintf(
                '/**
                * %s constructor.
                */',
               $this->convertToStudlyCaps($contentType->getId())
            ))
        );
    }

    /**
     * Generates the following code.
     *
     * ```
     * public function getX(string $locale = '<defaultLocale>')
     * {
     *     return $this->getField('x', $locale);
     * }
     * ```
     *
     * @param FieldInterface $field
     * @param string         $type
     *
     * @return ClassMethod
     */
    private function generateGetter(FieldInterface $field, string $type): ClassMethod
    {
        return new ClassMethod(
            'get'.$this->convertToStudlyCaps($field->getId()),
            [
                'flags' => Node\Stmt\Class_::MODIFIER_PUBLIC,
                'params' => [
                    new Node\Param('locale', new Node\Scalar\String_($this->defaultLocale), 'string'),
                ],
                'stmts' => [
                    new Node\Stmt\Return_(
                        new Node\Expr\MethodCall(
                            new Node\Expr\Variable('this'),
                            'getField',
                            [
                                new Node\Arg(new Node\Scalar\String_($field->getId())),
                                new Node\Arg(new Node\Expr\Variable('locale')),
                            ]
                        )
                    ),
                ],
            ],
            $this->generateCommentAttributes(\sprintf(
                "\n".'/**
                * Returns the "%s" field.
                *
                * @param string $locale
                *
                * @return %s|null
                */',
                $field->getId(),
                $type
            ))
        );
    }

    /**
     * Generates the following code.
     *
     * ```
     * public function setX(string $locale = '<defaultLocale>', <type> $value = null)
     * {
     *     return $this->setField('x', $locale, $value);
     * }
     * ```
     *
     * @param FieldInterface $field
     * @param string         $type
     *
     * @return ClassMethod
     */
    private function generateSetter(FieldInterface $field, string $type): ClassMethod
    {
        $methodType = $type == 'mixed'
            ? null
            : (\strpos($type, '[]') !== false ? 'array' : $type);

        return new ClassMethod(
            'set'.$this->convertToStudlyCaps($field->getId()),
            [
                'flags' => Node\Stmt\Class_::MODIFIER_PUBLIC,
                'params' => [
                    new Node\Param('locale', new Node\Scalar\String_($this->defaultLocale), 'string'),
                    new Node\Param('value', new Node\Expr\ConstFetch(new Node\Name('null')), $methodType),
                ],
                'stmts' => [
                    new Node\Stmt\Return_(
                        new Node\Expr\MethodCall(
                            new Node\Expr\Variable('this'),
                            'setField',
                            [
                                new Node\Arg(new Node\Scalar\String_($field->getId())),
                                new Node\Arg(new Node\Expr\Variable('locale')),
                                new Node\Arg(new Node\Expr\Variable('value')),
                            ]
                        )
                    ),
                ],
            ],
            $this->generateCommentAttributes(\sprintf(
                "\n".'/**
                * Sets the "%s" field.
                *
                * @param %s $locale
                * @param %s|null $value
                *
                * @return static
                */',
                $field->getId(),
                \str_pad('string', \strlen($type.'|null'), ' ', \STR_PAD_RIGHT),
                $type
            ))
        );
    }

    /**
     * Generates the following code.
     *
     * ```
     * public function resolveXLink(string $locale = '<defaultLocale>')
     * {
     *     return $this->proxy->resolveLink($this->getField('x', $locale));
     * }
     * ```
     *
     * @param LinkField $field
     *
     * @return ClassMethod
     */
    private function generateLinkResolverMethod(LinkField $field): ClassMethod
    {
        $returnType = $this->determineLinkReturnType($field->getLinkType(), $field->getValidations());

        $resolveLinkParameter = new Node\Expr\MethodCall(
            new Node\Expr\Variable('this'),
            'getField',
            [
                new Node\Arg(new Node\Scalar\String_($field->getId())),
                new Node\Arg(new Node\Expr\Variable('locale')),
            ]
        );

        return new ClassMethod(
            'resolve'.$this->convertToStudlyCaps($field->getId()).'Link',
            [
                'flags' => Node\Stmt\Class_::MODIFIER_PUBLIC,
                'params' => [
                    new Node\Param('locale', new Node\Scalar\String_($this->defaultLocale), 'string'),
                ],
                'stmts' => [
                    new Node\Stmt\Return_(
                        new Node\Expr\MethodCall(
                            new Node\Expr\PropertyFetch(new Node\Expr\Variable('this'), 'proxy'),
                            'resolveLink',
                            [
                                new Node\Arg($resolveLinkParameter),
                            ]
                        )
                    ),
                ],
            ],
            $this->generateCommentAttributes(\sprintf(
                "\n".'/**
                 * Returns the resolved "%s" link.
                 *
                 * @param string $locale
                 *
                 * @return %s
                 */',
                 $field->getId(),
                 $returnType
            ))
        );
    }

    /**
     * @param ArrayField $field
     *
     * @return ClassMethod
     */
    private function generateArrayLinkResolverMethod(ArrayField $field): ClassMethod
    {
        $returnTypes = $this->determineLinkReturnType($field->getItemsLinkType(), $field->getItemsValidations());

        return new ClassMethod(
            'resolve'.$this->convertToStudlyCaps($field->getId()).'Links',
            [
                'flags' => Node\Stmt\Class_::MODIFIER_PUBLIC,
                'params' => [
                    new Node\Param('locale', new Node\Scalar\String_($this->defaultLocale), 'string'),
                ],
                'stmts' => [
                    new Node\Stmt\Return_(
                        new Node\Expr\FuncCall(
                            new Node\Name('array_map'),
                            [
                                new Node\Arg($this->generateArrayLinkResolverClosure()),
                                new Node\Arg($this->generateArrayLinkResolverMapArray($field)),
                            ]
                        )
                    ),
                ],
            ],
            $this->generateCommentAttributes(\sprintf(
                "\n".'/**
                 * Returns an array of resolved "%s" links.
                 *
                 * @param string $locale
                 *
                 * @return %s[]
                 */',
                 $field->getId(),
                 \strpos($returnTypes, '|') !== false ? '('.$returnTypes.')' : $returnTypes
            ))
        );
    }

    /**
     * This method determines which type of link will be returned,
     * and using that information, a "use" statement will be set to true
     * so it will be added to the beginning of the file.
     *
     * @param string $linkType
     * @param array  $validations
     *
     * @return string Either "Asset", "ResourceInterface", or a list of values with "|" as separator
     */
    private function determineLinkReturnType(string $linkType, array $validations): string
    {
        $returnTypes = ['Asset'];
        $usesAsset = true;
        $usesResource = false;

        if ($linkType == 'Entry') {
            $returnTypes = ['ResourceInterface'];
            $usesAsset = false;
            $usesResource = true;

            foreach ($validations as $validation) {
                if ($validation instanceof LinkContentTypeValidation) {
                    $usesResource = false;
                    $returnTypes = \array_map(function (string $contentType) {
                        return $this->convertToStudlyCaps($contentType);
                    }, $validation->getContentTypes());

                    break;
                }
            }
        }

        if ($usesAsset) {
            $this->uses['asset'] = true;
        }
        if ($usesResource) {
            $this->uses['resource_interface'] = true;
        }

        return \implode('|', $returnTypes);
    }

    /**
     * @return Node\Expr
     */
    private function generateArrayLinkResolverClosure(): Node\Expr
    {
        return new Node\Expr\Closure([
            'params' => [
                new Node\Param('link', null, 'Link'),
            ],
            'stmts' => [
                new Node\Stmt\Return_(
                    new Node\Expr\MethodCall(
                        new Node\Expr\PropertyFetch(new Node\Expr\Variable('this'), 'proxy'),
                        'resolveLink',
                        [
                            new Node\Arg(new Node\Expr\Variable('link')),
                        ]
                    )
                ),
            ],
        ]);
    }

    /**
     * @param FieldInterface $field
     *
     * @return Node\Expr
     */
    private function generateArrayLinkResolverMapArray(FieldInterface $field): Node\Expr
    {
        return new Node\Expr\Cast\Array_(
            new Node\Expr\MethodCall(
                new Node\Expr\Variable('this'),
                'getField',
                [
                    new Node\Arg(new Node\Scalar\String_($field->getId())),
                    new Node\Arg(new Node\Expr\Variable('locale')),
                ]
            )
        );
    }
}
